# Accents
PRODUCT_PACKAGES += \
    Amber \
    Black \
    Blue \
    BlueGrey \
    brandOne \
    brandTwo \
    brandThree \
    brandFour \
    brandFive \
    brandSix \
    brandSeven \
    brandEight \
    brandNine \
    brandTen \
    brandEleven \
    brandTwelve \
    brandThirteen \
    brandFourteen \
    brandFifteen \
    brandSixteen \
    brandSeventeen \
    brandEighteen \
    brandNineteen \
    brandTwenty \
    Brown \
    Cyan \
    DeepOrange \
    DeepPurple \
    Green \
    Grey \
    Indigo \
    LightBlue \
    LightGreen \
    Lime \
    Orange \
    Pink \
    PixelBlue \
    Purple \
    qOne \
    qTwo \
    qThree \
    qFour \
    qFive \
    qSix \
    Red \
    Teal \
    Yellow \
    White
